# Generated by Django 5.2.11 on 2026-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-25', '18–25'), ('26-35', '26–35'), ('36-45', '36–45'), ('46-55', '46–55'), ('56-60', '56–60')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
